[build]
target = "index.html"
dist = "dist"

[watch]
watch = ["src", "index.html", "static"]
ignore = []

[serve]
address = "127.0.0.1"
port = 3200
open = false

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "cp -r static/* dist/ 2>/dev/null || true"]
